# Generated by Django 4.1 on 2022-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicios',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
