# Generated by Django 4.1 on 2022-09-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0003_ejercicios_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hablidad', models.CharField(max_length=200, verbose_name='Habilidad')),
            ],
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='subtitulo',
            field=models.CharField(max_length=50, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
