# Generated by Django 4.1 on 2022-09-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0006_alter_ejercicios_options_ejercicios_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicios',
            options={},
        ),
        migrations.RemoveField(
            model_name='habilidadejercicio',
            name='description',
        ),
    ]
