# Generated by Django 4.1 on 2022-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0007_alter_ejercicios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadejercicio',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo'),
        ),
    ]
