# Generated by Django 4.1 on 2022-09-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0008_habilidadejercicio_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicios',
            options={'ordering': ['-titulo'], 'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.RemoveField(
            model_name='ejercicios',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='dificultad',
            field=models.CharField(default=1, max_length=10, verbose_name='Dificultad'),
        ),
    ]
