# Generated by Django 4.1.1 on 2022-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0009_alter_ejercicios_options_remove_ejercicios_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidadejercicio',
            name='description',
        ),
        migrations.AddField(
            model_name='habilidadejercicio',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habilidades',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo'),
        ),
        migrations.AddField(
            model_name='habilidades',
            name='traduccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Traduccion'),
        ),
    ]
