# Generated by Django 4.1.1 on 2022-10-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanillaEjercicios', '0010_remove_habilidadejercicio_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidades',
            name='traduccion',
        ),
    ]
